### ISSUE TITLE
Folder Icons are missing in ST 3.0 build 3143

### ISSUE THREAD

**Issue by TheActualWalko** [jgroac/Sunrise-theme#2]
Other filetype icons are fine, but folders have disappeared. Other themes are working correctly.

<img width="749" alt="screen shot 2017-09-18 at 3 40 10 pm" src="https://user-images.githubusercontent.com/2360025/30561017-b1300fca-9c87-11e7-98d4-f170f2bbe608.png">

**Comment by jgroac** [comment]
apologize me for the delay, the new sublime version has changed a lot and broke my directory structure. i'm gonna take a look on this error and i'll send new version of the theme that solve the bug soon.

Thanks for reporting the bug.

**Comment by jgroac** [comment]
Hi the bug has been solved in the new release. 
Thanks a lot!
